### ISSUE TITLE
more tags

### ISSUE THREAD

**Issue by bryonpokemon** [DiscordFederation/DisboardScraper#2]
First thanks for the script works great, had a question tho, is there a way to put multiple tags like anime and community for example?

**Comment by daegontaven** [comment]
Unfortunately no. Disboard doesn't have a way to combine tags. What you can of however is load the data from the CSV file on two separate tags and combine them using pandas in the way you need to.

**Comment by bryonpokemon** [comment]
ahh damn i see, can you make one but for top.gg

**Comment by bryonpokemon** [comment]
nvm your prob busy with real life stuff
